# Generated by Django 5.2.10 on 2026-02-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalModelOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'original_model_output',
            },
        ),
        migrations.CreateModel(
            name='UserChangedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('original_output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_changes', to='pdf_converter.originalmodeloutput')),
            ],
            options={
                'db_table': 'user_changed_text',
            },
        ),
    ]
